//! Module Registration System
//!
//! This module implements automatic registration of ANI bindings,
//! similar to napi-rs's approach using the `ctor` crate.
//!
//! Functions marked with `#[ani]` are automatically registered at library load time,
//! and `ANI_Constructor` collects and executes all registrations.

use std::collections::BTreeMap;
use std::ffi::CString;
use std::os::raw::{c_char, c_void};
use std::sync::RwLock;

use crate::sys;

/// Registration callback type
/// Uses extern "C" to match the generated wrapper functions
pub type RegisterCallback = unsafe extern "C" fn(*mut sys::ani_env) -> sys::ani_status;

/// Module registration entry
#[derive(Clone)]
pub struct ModuleRegisterEntry {
    /// Function name (for debugging)
    pub name: &'static str,
    /// Registration callback
    pub callback: RegisterCallback,
}

/// Init callback registration entry
#[derive(Clone)]
pub struct InitRegisterEntry {
    /// Function name (for debugging)
    pub name: &'static str,
    /// Callback invoked during module initialization
    pub callback: RegisterCallback,
}

/// Native binding target description.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub enum ClassBindingScope {
    /// Instance member binding.
    Instance,
    /// Static member binding.
    Static,
}

/// Native binding target description.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub enum BindingTarget {
    /// Top-level module functions.
    Module(&'static str),
    /// Namespace functions.
    Namespace(&'static str),
    /// Class methods or accessors.
    Class {
        /// ANI class descriptor.
        descriptor: &'static str,
        /// Class member scope.
        scope: ClassBindingScope,
    },
}

impl BindingTarget {
    fn descriptor(self) -> &'static str {
        match self {
            Self::Module(descriptor) | Self::Namespace(descriptor) => descriptor,
            Self::Class { descriptor, .. } => descriptor,
        }
    }
}

/// Deferred binding entry collected during registration callbacks.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PendingBindingEntry {
    /// Binding destination.
    pub target: BindingTarget,
    /// Static function name.
    pub name: &'static str,
    /// Static function signature.
    pub signature: &'static str,
    /// Native callback function pointer.
    pub pointer: usize,
}

/// Global registry for module exports
static MODULE_REGISTER_CALLBACKS: RwLock<Vec<ModuleRegisterEntry>> = RwLock::new(Vec::new());
/// Global registry for init callbacks that run before native binding registration
static INIT_BEFORE_BINDINGS_CALLBACKS: RwLock<Vec<InitRegisterEntry>> = RwLock::new(Vec::new());
/// Global registry for init callbacks that run after native binding registration
static INIT_AFTER_BINDINGS_CALLBACKS: RwLock<Vec<InitRegisterEntry>> = RwLock::new(Vec::new());
/// Deferred native bindings collected from generated per-function callbacks.
static PENDING_BINDINGS: RwLock<Vec<PendingBindingEntry>> = RwLock::new(Vec::new());

/// Register a module export callback
///
/// This is called by `#[ctor]` functions generated by `#[ani]` macro
#[doc(hidden)]
pub fn register_module_export(name: &'static str, callback: RegisterCallback) {
    let entry = ModuleRegisterEntry { name, callback };
    MODULE_REGISTER_CALLBACKS
        .write()
        .expect("Failed to acquire write lock for MODULE_REGISTER_CALLBACKS")
        .push(entry);
}

/// Register an init callback.
///
/// If `before_bindings` is true, the callback runs before binding registration.
/// Otherwise, it runs after binding registration.
#[doc(hidden)]
pub fn register_init_callback(
    name: &'static str,
    before_bindings: bool,
    callback: RegisterCallback,
) {
    let entry = InitRegisterEntry { name, callback };
    let callbacks = if before_bindings {
        &INIT_BEFORE_BINDINGS_CALLBACKS
    } else {
        &INIT_AFTER_BINDINGS_CALLBACKS
    };

    callbacks
        .write()
        .expect("Failed to acquire write lock for init callbacks")
        .push(entry);
}

/// Queue a native binding export.
#[doc(hidden)]
pub fn queue_binding(
    target: BindingTarget,
    name: &'static str,
    signature: &'static str,
    pointer: *const c_void,
) -> sys::ani_status {
    let entry = PendingBindingEntry {
        target,
        name,
        signature,
        pointer: pointer as usize,
    };
    PENDING_BINDINGS
        .write()
        .expect("Failed to acquire write lock for PENDING_BINDINGS")
        .push(entry);
    sys::ani_status_ANI_OK
}

fn prepare_grouped_bindings(
    pending: &[PendingBindingEntry],
    debug: bool,
) -> std::result::Result<BTreeMap<BindingTarget, Vec<PendingBindingEntry>>, sys::ani_status> {
    let mut grouped: BTreeMap<BindingTarget, Vec<PendingBindingEntry>> = BTreeMap::new();
    for entry in pending.iter().copied() {
        grouped.entry(entry.target).or_default().push(entry);
    }

    for (target, entries) in grouped.iter_mut() {
        entries.sort_by(|lhs, rhs| {
            lhs.name
                .cmp(rhs.name)
                .then(lhs.signature.cmp(rhs.signature))
                .then(lhs.pointer.cmp(&rhs.pointer))
        });

        for pair in entries.windows(2) {
            let lhs = pair[0];
            let rhs = pair[1];
            if lhs.name == rhs.name && lhs.signature == rhs.signature {
                eprintln!(
                    "[ani] duplicate native binding target={target:?} name={} sig={} first_ptr={:p} second_ptr={:p}",
                    lhs.name,
                    lhs.signature,
                    lhs.pointer as *const c_void,
                    rhs.pointer as *const c_void
                );
                if debug {
                    eprintln!("[ani] duplicate binding aborting registration");
                }
                return Err(sys::ani_status_ANI_ALREADY_BINDED);
            }
        }
    }

    Ok(grouped)
}

/// Queue a module-level native function binding.
#[doc(hidden)]
pub fn queue_module_binding(
    descriptor: &'static str,
    name: &'static str,
    signature: &'static str,
    pointer: *const c_void,
) -> sys::ani_status {
    queue_binding(BindingTarget::Module(descriptor), name, signature, pointer)
}

/// Queue a namespace native function binding.
#[doc(hidden)]
pub fn queue_namespace_binding(
    descriptor: &'static str,
    name: &'static str,
    signature: &'static str,
    pointer: *const c_void,
) -> sys::ani_status {
    queue_binding(
        BindingTarget::Namespace(descriptor),
        name,
        signature,
        pointer,
    )
}

/// Queue a class native method binding.
#[doc(hidden)]
pub fn queue_class_binding(
    descriptor: &'static str,
    scope: ClassBindingScope,
    name: &'static str,
    signature: &'static str,
    pointer: *const c_void,
) -> sys::ani_status {
    queue_binding(
        BindingTarget::Class { descriptor, scope },
        name,
        signature,
        pointer,
    )
}

const DEFMODULE_PREFIX: &str = "@defModule.";

fn is_builtin_descriptor(descriptor: &str) -> bool {
    descriptor.starts_with("std.")
        || descriptor.starts_with("escompat.")
        || descriptor.starts_with("arkts.")
        || descriptor.starts_with("@")
}

fn test_module_override_name() -> Option<String> {
    std::env::var("ANI_TEST_MODULE_NAME")
        .ok()
        .map(|value| value.trim().replace('-', "_"))
        .filter(|value| !value.is_empty())
}

fn override_descriptor_for_test(descriptor: &str) -> Option<String> {
    let override_name = test_module_override_name()?;
    let trimmed = descriptor.trim();
    if trimmed.is_empty()
        || is_builtin_descriptor(trimmed)
        || trimmed.starts_with(DEFMODULE_PREFIX)
        || trimmed == override_name
        || trimmed.starts_with(&format!("{override_name}."))
    {
        return None;
    }

    let suffix = trimmed
        .split_once('.')
        .map(|(_, rest)| format!(".{rest}"))
        .unwrap_or_default();
    Some(format!("{override_name}{suffix}"))
}

fn descriptor_candidates(descriptor: &str) -> Vec<String> {
    let trimmed = descriptor.trim();
    if trimmed.is_empty() {
        return Vec::new();
    }

    let mut out = Vec::new();
    if let Some(override_descriptor) = override_descriptor_for_test(trimmed) {
        out.push(override_descriptor.clone());
        out.push(format!("{DEFMODULE_PREFIX}{override_descriptor}"));
    }

    out.push(trimmed.to_string());
    if !is_builtin_descriptor(trimmed) && !trimmed.starts_with(DEFMODULE_PREFIX) {
        // Some test suites use @defModule-prefixed descriptors.
        // Keep it as a fallback only after raw dotted descriptor.
        out.push(format!("{DEFMODULE_PREFIX}{trimmed}"));
    }
    out
}

unsafe fn reset_pending_error_if_any(
    api: &sys::__ani_interaction_api,
    env: *mut sys::ani_env,
    debug: bool,
) {
    let Some(exist_unhandled) = api.ExistUnhandledError else {
        return;
    };
    let Some(reset_error) = api.ResetError else {
        return;
    };

    let mut has_unhandled: sys::ani_boolean = 0;
    let status = unsafe { exist_unhandled(env, &mut has_unhandled) };
    if status != sys::ani_status_ANI_OK || has_unhandled == 0 {
        return;
    }

    let reset_status = unsafe { reset_error(env) };
    if debug {
        eprintln!("[ani] ResetError status={reset_status}");
    }
}

unsafe fn find_module_with_fallback(
    api: &sys::__ani_interaction_api,
    env: *mut sys::ani_env,
    descriptor: &str,
    debug: bool,
) -> (sys::ani_status, sys::ani_module) {
    let candidates = descriptor_candidates(descriptor);
    if candidates.is_empty() {
        return (sys::ani_status_ANI_OK, std::ptr::null_mut());
    }

    let mut last_status = sys::ani_status_ANI_NOT_FOUND;
    for candidate in candidates {
        let c_descriptor = match CString::new(candidate.as_bytes()) {
            Ok(v) => v,
            Err(_) => return (sys::ani_status_ANI_INVALID_ARGS, std::ptr::null_mut()),
        };
        let mut module: sys::ani_module = std::ptr::null_mut();
        let status = unsafe { (api.FindModule.unwrap())(env, c_descriptor.as_ptr(), &mut module) };
        if debug {
            eprintln!("[ani] FindModule descriptor={candidate} status={status} ptr={module:p}");
        }
        if status == sys::ani_status_ANI_OK && !module.is_null() {
            return (status, module);
        }
        if status != sys::ani_status_ANI_OK {
            unsafe { reset_pending_error_if_any(api, env, debug) };
        }
        last_status = status;
    }

    (last_status, std::ptr::null_mut())
}

unsafe fn find_namespace_with_fallback(
    api: &sys::__ani_interaction_api,
    env: *mut sys::ani_env,
    descriptor: &str,
    debug: bool,
) -> (sys::ani_status, sys::ani_namespace) {
    let candidates = descriptor_candidates(descriptor);
    if candidates.is_empty() {
        return (sys::ani_status_ANI_INVALID_ARGS, std::ptr::null_mut());
    }

    let mut last_status = sys::ani_status_ANI_NOT_FOUND;
    for candidate in candidates {
        let c_descriptor = match CString::new(candidate.as_bytes()) {
            Ok(v) => v,
            Err(_) => return (sys::ani_status_ANI_INVALID_ARGS, std::ptr::null_mut()),
        };
        let mut ns: sys::ani_namespace = std::ptr::null_mut();
        let status = unsafe { (api.FindNamespace.unwrap())(env, c_descriptor.as_ptr(), &mut ns) };
        if debug {
            eprintln!("[ani] FindNamespace descriptor={candidate} status={status} ptr={ns:p}");
        }
        if status == sys::ani_status_ANI_OK && !ns.is_null() {
            return (status, ns);
        }
        if status != sys::ani_status_ANI_OK {
            unsafe { reset_pending_error_if_any(api, env, debug) };
        }
        last_status = status;
    }

    (last_status, std::ptr::null_mut())
}

unsafe fn find_class_with_fallback(
    api: &sys::__ani_interaction_api,
    env: *mut sys::ani_env,
    descriptor: &str,
    debug: bool,
) -> (sys::ani_status, sys::ani_class) {
    let candidates = descriptor_candidates(descriptor);
    if candidates.is_empty() {
        return (sys::ani_status_ANI_INVALID_ARGS, std::ptr::null_mut());
    }

    let mut last_status = sys::ani_status_ANI_NOT_FOUND;
    for candidate in candidates {
        let c_descriptor = match CString::new(candidate.as_bytes()) {
            Ok(v) => v,
            Err(_) => return (sys::ani_status_ANI_INVALID_ARGS, std::ptr::null_mut()),
        };
        let mut cls: sys::ani_class = std::ptr::null_mut();
        let status = unsafe { (api.FindClass.unwrap())(env, c_descriptor.as_ptr(), &mut cls) };
        if debug {
            eprintln!("[ani] FindClass descriptor={candidate} status={status} ptr={cls:p}");
        }
        if status == sys::ani_status_ANI_OK && !cls.is_null() {
            return (status, cls);
        }
        if status != sys::ani_status_ANI_OK {
            unsafe { reset_pending_error_if_any(api, env, debug) };
        }
        last_status = status;
    }

    (last_status, std::ptr::null_mut())
}

/// Execute init callbacks that should run before native binding registration.
#[doc(hidden)]
pub unsafe fn execute_before_bindings_inits(env: *mut sys::ani_env) -> sys::ani_status {
    let callbacks = INIT_BEFORE_BINDINGS_CALLBACKS
        .read()
        .expect("Failed to acquire read lock for INIT_BEFORE_BINDINGS_CALLBACKS");

    for entry in callbacks.iter() {
        // SAFETY: The callback is a function pointer registered via #[ani(init)] macro
        let status = unsafe { (entry.callback)(env) };
        if status != sys::ani_status_ANI_OK {
            eprintln!("Failed to run before_bindings init: {}", entry.name);
            return status;
        }
    }

    sys::ani_status_ANI_OK
}

/// Execute all registered callbacks
///
/// Called by `ANI_Constructor` to bind all native functions
#[doc(hidden)]
pub unsafe fn execute_registrations(env: *mut sys::ani_env) -> sys::ani_status {
    let callbacks = MODULE_REGISTER_CALLBACKS
        .read()
        .expect("Failed to acquire read lock for MODULE_REGISTER_CALLBACKS");
    let debug = std::env::var("ANI_DEBUG_REGISTER").ok().as_deref() == Some("1");
    PENDING_BINDINGS
        .write()
        .expect("Failed to acquire write lock for PENDING_BINDINGS")
        .clear();

    if debug {
        eprintln!("[ani] execute_registrations count={}", callbacks.len());
    }

    for entry in callbacks.iter() {
        if debug {
            eprintln!("[ani] register begin: {}", entry.name);
        }
        // SAFETY: The callback is a function pointer registered via #[ani] macro
        let status = unsafe { (entry.callback)(env) };
        if debug {
            eprintln!("[ani] register end: {} status={}", entry.name, status);
        }
        if status != sys::ani_status_ANI_OK {
            eprintln!(
                "Failed to register function: {} (status={})",
                entry.name, status
            );
            return status;
        }
    }

    let pending = PENDING_BINDINGS
        .read()
        .expect("Failed to acquire read lock for PENDING_BINDINGS");

    let grouped = match prepare_grouped_bindings(&pending, debug) {
        Ok(grouped) => grouped,
        Err(status) => return status,
    };
    drop(pending);

    if grouped.is_empty() {
        if debug {
            eprintln!("[ani] no pending bindings");
        }
        return sys::ani_status_ANI_OK;
    }

    let api = unsafe {
        // SAFETY: `env` comes from ANI entrypoints and is expected to be a valid
        // pointer to `ani_env`, whose first field points to API table.
        &*(*env)
    };
    for (target, entries) in grouped {
        let functions = entries
            .iter()
            .map(|entry| sys::ani_native_function {
                name: entry.name.as_ptr() as *const c_char,
                signature: entry.signature.as_ptr() as *const c_char,
                pointer: entry.pointer as *const c_void,
            })
            .collect::<Vec<_>>();
        if debug {
            eprintln!(
                "[ani] bind target={target:?} descriptor={} count={}",
                target.descriptor(),
                functions.len()
            );
            for (idx, (entry, f)) in entries.iter().zip(functions.iter()).enumerate() {
                eprintln!(
                    "[ani]   fn[{idx}] name={name} sig={sig} ptr={:p}",
                    f.pointer,
                    name = entry.name,
                    sig = entry.signature
                );
            }
        }

        let status = match target {
            BindingTarget::Class { descriptor, scope } => {
                let (status, cls) =
                    unsafe { find_class_with_fallback(api, env, descriptor, debug) };
                if status != sys::ani_status_ANI_OK {
                    status
                } else if cls.is_null() {
                    sys::ani_status_ANI_NOT_FOUND
                } else {
                    match scope {
                        ClassBindingScope::Static => unsafe {
                            (api.Class_BindStaticNativeMethods.unwrap())(
                                env,
                                cls,
                                functions.as_ptr(),
                                functions.len(),
                            )
                        },
                        ClassBindingScope::Instance => unsafe {
                            (api.Class_BindNativeMethods.unwrap())(
                                env,
                                cls,
                                functions.as_ptr(),
                                functions.len(),
                            )
                        },
                    }
                }
            }
            BindingTarget::Namespace(descriptor) => {
                let (status, ns) =
                    unsafe { find_namespace_with_fallback(api, env, descriptor, debug) };
                if status != sys::ani_status_ANI_OK {
                    status
                } else if ns.is_null() {
                    sys::ani_status_ANI_NOT_FOUND
                } else {
                    unsafe {
                        (api.Namespace_BindNativeFunctions.unwrap())(
                            env,
                            ns,
                            functions.as_ptr(),
                            functions.len(),
                        )
                    }
                }
            }
            BindingTarget::Module(descriptor) => {
                if descriptor.is_empty() {
                    sys::ani_status_ANI_INVALID_ARGS
                } else {
                    let (status, module) =
                        unsafe { find_module_with_fallback(api, env, descriptor, debug) };
                    if status != sys::ani_status_ANI_OK {
                        status
                    } else if module.is_null() {
                        sys::ani_status_ANI_NOT_FOUND
                    } else {
                        if debug {
                            for (idx, f) in functions.iter().enumerate() {
                                let mut found: sys::ani_function = core::ptr::null_mut();
                                let check_status = unsafe {
                                    (api.Module_FindFunction.unwrap())(
                                        env,
                                        module,
                                        f.name,
                                        f.signature,
                                        &mut found,
                                    )
                                };
                                eprintln!(
                                    "[ani]   precheck module fn[{idx}] find_status={check_status} ptr={found:p}"
                                );
                            }
                        }
                        unsafe {
                            (api.Module_BindNativeFunctions.unwrap())(
                                env,
                                module,
                                functions.as_ptr(),
                                functions.len(),
                            )
                        }
                    }
                }
            }
        };

        if debug {
            eprintln!("[ani] bind done target={target:?} status={status}");
        }

        if status != sys::ani_status_ANI_OK {
            return status;
        }
    }

    sys::ani_status_ANI_OK
}

/// Execute init callbacks that should run after native binding registration.
#[doc(hidden)]
pub unsafe fn execute_after_bindings_inits(env: *mut sys::ani_env) -> sys::ani_status {
    let callbacks = INIT_AFTER_BINDINGS_CALLBACKS
        .read()
        .expect("Failed to acquire read lock for INIT_AFTER_BINDINGS_CALLBACKS");

    for entry in callbacks.iter() {
        // SAFETY: The callback is a function pointer registered via #[ani(init)] macro
        let status = unsafe { (entry.callback)(env) };
        if status != sys::ani_status_ANI_OK {
            eprintln!("Failed to run after_bindings init: {}", entry.name);
            return status;
        }
    }

    sys::ani_status_ANI_OK
}

/// Get the number of registered callbacks (for debugging)
#[doc(hidden)]
pub fn registered_count() -> usize {
    MODULE_REGISTER_CALLBACKS
        .read()
        .expect("Failed to acquire read lock for MODULE_REGISTER_CALLBACKS")
        .len()
}

/// Clear all registered callbacks (for testing)
#[cfg(test)]
#[doc(hidden)]
pub fn clear_registrations() {
    MODULE_REGISTER_CALLBACKS
        .write()
        .expect("Failed to acquire write lock for MODULE_REGISTER_CALLBACKS")
        .clear();
    INIT_BEFORE_BINDINGS_CALLBACKS
        .write()
        .expect("Failed to acquire write lock for INIT_BEFORE_BINDINGS_CALLBACKS")
        .clear();
    INIT_AFTER_BINDINGS_CALLBACKS
        .write()
        .expect("Failed to acquire write lock for INIT_AFTER_BINDINGS_CALLBACKS")
        .clear();
    PENDING_BINDINGS
        .write()
        .expect("Failed to acquire write lock for PENDING_BINDINGS")
        .clear();
}

#[cfg(test)]
mod tests {
    use super::*;
    use core::ptr;
    use std::sync::{Mutex, MutexGuard};

    static TEST_LOCK: Mutex<()> = Mutex::new(());

    struct TestEnvVarGuard {
        key: String,
        previous: Option<String>,
        _lock: MutexGuard<'static, ()>,
    }

    impl TestEnvVarGuard {
        fn unset(key: &str) -> Self {
            let lock = TEST_LOCK.lock().expect("lock test mutex");
            let previous = std::env::var(key).ok();
            // Safety: tests holding this guard serialize process-wide env mutation.
            unsafe {
                std::env::remove_var(key);
            }
            Self {
                key: key.to_string(),
                previous,
                _lock: lock,
            }
        }

        fn set(key: &str, value: &str) -> Self {
            let lock = TEST_LOCK.lock().expect("lock test mutex");
            let previous = std::env::var(key).ok();
            // Safety: tests holding this guard serialize process-wide env mutation.
            unsafe {
                std::env::set_var(key, value);
            }
            Self {
                key: key.to_string(),
                previous,
                _lock: lock,
            }
        }
    }

    impl Drop for TestEnvVarGuard {
        fn drop(&mut self) {
            // Safety: tests holding this guard serialize process-wide env mutation.
            unsafe {
                match &self.previous {
                    Some(previous) => std::env::set_var(&self.key, previous),
                    None => std::env::remove_var(&self.key),
                }
            }
        }
    }

    #[test]
    fn descriptor_candidates_non_builtin_has_defmodule_fallback() {
        let _guard = TestEnvVarGuard::unset("ANI_TEST_MODULE_NAME");
        let candidates = descriptor_candidates("a.b.C");
        assert_eq!(
            candidates,
            vec!["a.b.C".to_string(), "@defModule.a.b.C".to_string()]
        );
    }

    #[test]
    fn descriptor_candidates_builtin_has_no_defmodule_fallback() {
        let _guard = TestEnvVarGuard::unset("ANI_TEST_MODULE_NAME");
        let candidates = descriptor_candidates("std.core.String");
        assert_eq!(candidates, vec!["std.core.String".to_string()]);
    }

    #[test]
    fn descriptor_candidates_respect_test_override_for_explicit_module_binding() {
        let _guard = TestEnvVarGuard::set("ANI_TEST_MODULE_NAME", "arkvm_test");

        let candidates = descriptor_candidates("explicit_module_binding");
        assert_eq!(
            candidates,
            vec![
                "arkvm_test".to_string(),
                "@defModule.arkvm_test".to_string(),
                "explicit_module_binding".to_string(),
                "@defModule.explicit_module_binding".to_string()
            ]
        );
    }

    #[test]
    fn descriptor_candidates_preserve_suffix_when_test_override_is_active() {
        let _guard = TestEnvVarGuard::set("ANI_TEST_MODULE_NAME", "arkvm_test");

        let candidates = descriptor_candidates("custom.entry.module");
        assert_eq!(
            candidates,
            vec![
                "arkvm_test.entry.module".to_string(),
                "@defModule.arkvm_test.entry.module".to_string(),
                "custom.entry.module".to_string(),
                "@defModule.custom.entry.module".to_string()
            ]
        );
    }

    #[test]
    fn queue_class_binding_sets_target_kind() {
        let _guard = TEST_LOCK.lock().expect("lock test mutex");
        clear_registrations();

        let status = queue_binding(
            BindingTarget::Class {
                descriptor: "demo.Test",
                scope: ClassBindingScope::Instance,
            },
            "m1",
            ":",
            ptr::null(),
        );
        assert_eq!(status, sys::ani_status_ANI_OK);
        let status = queue_binding(
            BindingTarget::Class {
                descriptor: "demo.Test",
                scope: ClassBindingScope::Static,
            },
            "m2",
            ":",
            ptr::null(),
        );
        assert_eq!(status, sys::ani_status_ANI_OK);

        let pending = PENDING_BINDINGS.read().expect("read pending");
        assert_eq!(pending.len(), 2);
        assert_eq!(
            pending[0].target,
            BindingTarget::Class {
                descriptor: "demo.Test",
                scope: ClassBindingScope::Instance
            }
        );
        assert_eq!(
            pending[1].target,
            BindingTarget::Class {
                descriptor: "demo.Test",
                scope: ClassBindingScope::Static
            }
        );

        drop(pending);
        clear_registrations();
    }

    #[test]
    fn prepare_grouped_bindings_sorts_entries_deterministically() {
        let _guard = TEST_LOCK.lock().expect("lock test mutex");
        clear_registrations();

        let target = BindingTarget::Module("demo.Entry");
        let _ = queue_binding(target, "zeta", "I:I", 3usize as *const c_void);
        let _ = queue_binding(target, "alpha", "J:J", 2usize as *const c_void);
        let _ = queue_binding(target, "alpha", "I:I", std::ptr::dangling::<c_void>());

        let pending = PENDING_BINDINGS.read().expect("read pending");
        let grouped = prepare_grouped_bindings(&pending, false).expect("grouping should succeed");
        let functions = grouped.get(&target).expect("target must exist");
        let order = functions
            .iter()
            .map(|entry| (entry.name, entry.signature, entry.pointer))
            .collect::<Vec<_>>();
        assert_eq!(
            order,
            vec![("alpha", "I:I", 1), ("alpha", "J:J", 2), ("zeta", "I:I", 3)]
        );
    }

    #[test]
    fn prepare_grouped_bindings_rejects_duplicate_name_and_signature_per_target() {
        let _guard = TEST_LOCK.lock().expect("lock test mutex");
        clear_registrations();

        let target = BindingTarget::Namespace("demo.ns");
        let _ = queue_binding(target, "dup", "I:I", std::ptr::dangling::<c_void>());
        let _ = queue_binding(target, "dup", "I:I", 2usize as *const c_void);

        let pending = PENDING_BINDINGS.read().expect("read pending");
        let status =
            prepare_grouped_bindings(&pending, false).expect_err("duplicate should be rejected");
        assert_eq!(status, sys::ani_status_ANI_ALREADY_BINDED);
    }

    #[test]
    fn prepare_grouped_bindings_allows_same_name_and_signature_for_distinct_targets() {
        let _guard = TEST_LOCK.lock().expect("lock test mutex");
        clear_registrations();

        let _ = queue_binding(
            BindingTarget::Module("demo.Entry"),
            "same",
            "I:I",
            std::ptr::dangling::<c_void>(),
        );
        let _ = queue_binding(
            BindingTarget::Namespace("demo.ns"),
            "same",
            "I:I",
            2usize as *const c_void,
        );

        let pending = PENDING_BINDINGS.read().expect("read pending");
        let grouped = prepare_grouped_bindings(&pending, false).expect("targets should coexist");
        assert_eq!(grouped.len(), 2);
    }
}
