//! Module Registration System
//!
//! This module implements automatic registration of ANI bindings,
//! similar to napi-rs's approach using the `ctor` crate.
//!
//! Functions marked with `#[ani]` are automatically registered at library load time,
//! and `ANI_Constructor` collects and executes all registrations.

use std::sync::RwLock;

use crate::sys;

/// Registration callback type
/// Uses extern "C" to match the generated wrapper functions
pub type RegisterCallback = unsafe extern "C" fn(*mut sys::ani_env) -> sys::ani_status;

/// Module registration entry
#[derive(Clone)]
pub struct ModuleRegisterEntry {
    /// Function name (for debugging)
    pub name: &'static str,
    /// Registration callback
    pub callback: RegisterCallback,
}

/// Global registry for module exports
static MODULE_REGISTER_CALLBACKS: RwLock<Vec<ModuleRegisterEntry>> = RwLock::new(Vec::new());

/// Register a module export callback
///
/// This is called by `#[ctor]` functions generated by `#[ani]` macro
#[doc(hidden)]
pub fn register_module_export(name: &'static str, callback: RegisterCallback) {
    let entry = ModuleRegisterEntry { name, callback };
    MODULE_REGISTER_CALLBACKS
        .write()
        .expect("Failed to acquire write lock for MODULE_REGISTER_CALLBACKS")
        .push(entry);
}

/// Execute all registered callbacks
///
/// Called by `ANI_Constructor` to bind all native functions
#[doc(hidden)]
pub unsafe fn execute_registrations(env: *mut sys::ani_env) -> sys::ani_status {
    let callbacks = MODULE_REGISTER_CALLBACKS
        .read()
        .expect("Failed to acquire read lock for MODULE_REGISTER_CALLBACKS");

    for entry in callbacks.iter() {
        // SAFETY: The callback is a function pointer registered via #[ani] macro
        let status = unsafe { (entry.callback)(env) };
        if status != sys::ani_status_ANI_OK {
            eprintln!("Failed to register function: {}", entry.name);
            return status;
        }
    }

    sys::ani_status_ANI_OK
}

/// Get the number of registered callbacks (for debugging)
#[doc(hidden)]
pub fn registered_count() -> usize {
    MODULE_REGISTER_CALLBACKS
        .read()
        .expect("Failed to acquire read lock for MODULE_REGISTER_CALLBACKS")
        .len()
}

/// Clear all registered callbacks (for testing)
#[cfg(test)]
#[doc(hidden)]
pub fn clear_registrations() {
    MODULE_REGISTER_CALLBACKS
        .write()
        .expect("Failed to acquire write lock for MODULE_REGISTER_CALLBACKS")
        .clear();
}
