//! # ANI Derive Macros
//!
//! Provides simple and easy-to-use macros similar to napi-rs for generating ANI binding code.
//!
//! ## Architecture
//!
//! The crate is organized into the following modules:
//!
//! - **parser**: Attribute parsing (`#[ani(...)]` attributes)
//! - **types**: Type conversion and signature generation
//! - **codegen**: Code generation (wrappers, registration functions)
//! - **expand**: Macro expansion for functions, impl blocks, and structs
//!
//! ## Usage Examples
//!
//! ```rust,ignore
//! use ani_derive::ani;
//!
//! // Module-level function
//! #[ani]
//! fn add(a: i32, b: i32) -> i32 {
//!     a + b
//! }
//!
//! // Class method
//! #[ani(class = "Calculator")]
//! fn multiply(&self, a: f64, b: f64) -> f64 {
//!     a * b
//! }
//!
//! // Namespace function
//! #[ani(namespace = "Math")]
//! fn sqrt(x: f64) -> f64 {
//!     x.sqrt()
//! }
//!
//! // Initialization function
//! #[ani(init)]
//! fn setup() {
//!     println!("Module initialized!");
//! }
//! ```
//!
//! ## No Manual Module Registration Required!
//!
//! Unlike earlier versions, you no longer need to use `ani_module!` macro.
//! The `ANI_Constructor` entry point is automatically generated when
//! you use the first `#[ani]` macro in your crate.
//!
//! The module name is automatically derived from `CARGO_PKG_NAME`.

use proc_macro::TokenStream;
use std::sync::atomic::{AtomicBool, Ordering};
use syn::{DeriveInput, ItemFn, ItemImpl, ItemStruct, parse_macro_input};

// Module organization following napi-rs pattern
mod codegen;
mod expand;
mod parser;
mod types;

use expand::{expand_class_derive, expand_function, expand_impl, expand_init, expand_struct};
use parser::{AniAttrs, AniMacroKind, BindgenAttrs, InitAttrs};

/// Tracks whether this is the first #[ani] macro invocation in the crate
/// Used to auto-generate ANI_Constructor only once
static IS_FIRST_ANI_MACRO: AtomicBool = AtomicBool::new(true);

/// Generate auto-registration code for ANI_Constructor
/// This is called only on the first #[ani] macro invocation
fn generate_constructor_code() -> proc_macro2::TokenStream {
    if IS_FIRST_ANI_MACRO.swap(false, Ordering::SeqCst) {
        let name = std::env::var("CARGO_PKG_NAME")
            .unwrap_or_else(|_| String::from("entry"))
            .replace('-', "_");

        quote::quote! {
            /// ANI module constructor - auto-generated by the first #[ani] macro
            ///
            /// Called automatically when ArkTS invokes loadLibrary.
            /// This function executes all registrations collected via #[ani] macro.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn ANI_Constructor(
                vm: *mut ::ani::sys::ani_vm,
                result: *mut u32,
            ) -> ::ani::sys::ani_status {
                unsafe {
                    let api = &*(*vm);
                    let mut env: *mut ::ani::sys::ani_env = std::ptr::null_mut();

                    let status = (api.GetEnv.unwrap())(vm, ::ani::sys::ANI_VERSION_1, &mut env);
                    if status != ::ani::sys::ani_status_ANI_OK {
                        return status;
                    }

                    let status = ::ani::module_register::execute_registrations(env);
                    if status != ::ani::sys::ani_status_ANI_OK {
                        return status;
                    }

                    *result = ::ani::sys::ANI_VERSION_1;
                    ::ani::sys::ani_status_ANI_OK
                }
            }

            /// Module name constant (auto-generated from CARGO_PKG_NAME)
            pub const ANI_MODULE_NAME: &str = #name;
        }
    } else {
        quote::quote! {}
    }
}

/// Unified ANI binding macro
///
/// Exports Rust functions, structs, and impl blocks as ArkTS native bindings.
/// Supports module-level functions, class methods, namespaces, and more.
///
/// # Basic Usage (Function Binding)
///
/// - `#[ani]` - Bind to module level
/// - `#[ani(namespace = "MyNamespace")]` - Bind to namespace
/// - `#[ani(class = "MyClass")]` - Bind as class instance method
/// - `#[ani(class = "MyClass", static)]` - Bind as class static method
/// - `#[ani(class = "MyClass", constructor)]` - Bind as constructor
/// - `#[ani(getter = "propertyName")]` - Bind as property getter
/// - `#[ani(setter = "propertyName")]` - Bind as property setter
///
/// # Initialization Function
///
/// - `#[ani(init)]` - Mark as initialization function (called during module load)
/// - `#[ani(init, before_bindings)]` - Call before bindings are registered
///
/// # Object/Class Definition
///
/// - `#[ani(object)]` - Define ANI object type
/// - `#[ani(object = "CustomName")]` - Use custom name
///
/// # Examples
///
/// ```rust,ignore
/// // Module-level function
/// #[ani]
/// fn greet(name: String) -> String {
///     format!("Hello, {}!", name)
/// }
///
/// // Class instance method
/// #[ani(class = "Person")]
/// fn get_age(this: i64) -> i32 {
///     42
/// }
///
/// // Initialization function
/// #[ani(init)]
/// fn setup() {
///     println!("Module initialized!");
/// }
///
/// // Object definition
/// #[ani(object)]
/// struct Person {
///     name: String,
///     age: i32,
/// }
/// ```
#[proc_macro_attribute]
pub fn ani(attr: TokenStream, item: TokenStream) -> TokenStream {
    let attrs = parse_macro_input!(attr as AniAttrs);
    let prepare = generate_constructor_code();

    match attrs.kind {
        AniMacroKind::Init => {
            if let Ok(func) = syn::parse::<ItemFn>(item.clone()) {
                return expand_init(InitAttrs::from(attrs), func, prepare).into();
            }
            syn::Error::new_spanned(
                proc_macro2::TokenStream::from(item),
                "#[ani(init)] can only be applied to functions",
            )
            .to_compile_error()
            .into()
        }
        AniMacroKind::Object => {
            if let Ok(struct_item) = syn::parse::<ItemStruct>(item.clone()) {
                let mut bindgen_attrs = BindgenAttrs::from(attrs.clone());
                if let Some(ref obj_name) = attrs.object_name {
                    bindgen_attrs.class = Some(obj_name.clone());
                }
                return expand_struct(bindgen_attrs, struct_item, prepare).into();
            }
            syn::Error::new_spanned(
                proc_macro2::TokenStream::from(item),
                "#[ani(object)] can only be applied to structs",
            )
            .to_compile_error()
            .into()
        }
        AniMacroKind::Bindgen => {
            let bindgen_attrs = BindgenAttrs::from(attrs);

            // Try to parse as function
            if let Ok(func) = syn::parse::<ItemFn>(item.clone()) {
                return expand_function(bindgen_attrs, func, prepare).into();
            }

            // Try to parse as impl block
            if let Ok(impl_block) = syn::parse::<ItemImpl>(item.clone()) {
                return expand_impl(bindgen_attrs, impl_block, prepare).into();
            }

            // Try to parse as struct
            if let Ok(struct_item) = syn::parse::<ItemStruct>(item.clone()) {
                return expand_struct(bindgen_attrs, struct_item, prepare).into();
            }

            syn::Error::new_spanned(
                proc_macro2::TokenStream::from(item),
                "#[ani] can only be applied to functions, impl blocks, or structs",
            )
            .to_compile_error()
            .into()
        }
    }
}

/// Derive macro to generate ANI class bindings for structs
///
/// # Examples
///
/// ```rust,ignore
/// #[derive(AniClass)]
/// #[ani(class = "Person")]
/// struct Person {
///     #[ani(getter, setter)]
///     name: String,
///     
///     #[ani(getter)]
///     age: i32,
/// }
/// ```
#[proc_macro_derive(AniClass, attributes(ani))]
pub fn derive_ani_class(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    expand_class_derive(input).into()
}
