[package]
name = "ani-example-async-wrapper"
version = "0.1.0"
publish = false
license.workspace = true
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ani = { workspace = true, features = ["async"] }
ani-derive = { workspace = true }
tokio = { version = "1", default-features = false, features = ["time"] }
